/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import ProfiniteGroupsTests.PrimewisePadicIdealTransport
public import ProfiniteGroupsTests.CompatibleSubgroups
public import ProfiniteGroupsTests.CompatibleSylow
public import ProfiniteGroupsTests.ClosedSylow
public import ProfiniteGroupsTests.ClosedQuotient
public import ProfiniteGroupsTests.FiniteQuotientConjugacy
public import ProfiniteGroupsTests.PrimewisePadicKernelTransport
public import ProfiniteGroupsTests.PrimewisePadicQuotients
public import ProfiniteGroupsTests.ProcyclicBaseMap
public import ProfiniteGroupsTests.ProcyclicGeneratorIndependence
public import ProfiniteGroupsTests.ProcyclicHom
public import ProfiniteGroupsTests.ProcyclicInvariant
public import ProfiniteGroupsTests.ProcyclicPower
public import ProfiniteGroupsTests.ProcyclicPowerIndex
public import ProfiniteGroupsTests.ProcyclicPowerTransition
public import ProfiniteGroupsTests.ProcyclicClosedSubgroup
public import ProfiniteGroupsTests.ProcyclicQuotient
public import ProfiniteGroupsTests.ProcyclicRealization
public import ProfiniteGroupsTests.ProcyclicTorsionFree
public import ProfiniteGroupsTests.ProcyclicTorsionFreeProduct
public import ProfiniteGroupsTests.PublicRoot
public import ProfiniteGroupsTests.DirectImports

/-!
# Test and client aggregation

Proof-using examples and standalone public API clients are default-built through
this root. The production root never imports tests.
-/
