/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import ProfiniteGroups.ProcyclicPowerTransition
public import ProfiniteGroups.ProcyclicTorsionFreeProduct
public import Mathlib.NumberTheory.SmoothNumbers
import Mathlib.Algebra.Group.Submonoid.BigOperators

/-!
# Prime-supported indices of procyclic power images

The positive integers supported on a set of primes form the submonoid generated
by those primes. For a torsion-free procyclic profinite group, the relevant
primes are those whose generator-independent exponents are infinite. Positive
power-image indices and indices of open subgroups are expressed using this
submonoid. The zero index is excluded: at infinite index the equality between
an index and a zero exponent need not imply exactness in the positive sense.

## References

- Neukirch–Schmidt–Wingberg, *Cohomology of Number Fields*, Ch. I §7, before Proposition
  (1.7.7) (supported positive power indices for torsion-free procyclic groups).
- Mathlib, `Mathlib.NumberTheory.SmoothNumbers` and
  `Mathlib.Algebra.Group.Submonoid.BigOperators` (supported integers as a prime-generated
  submonoid).
-/

@[expose] public section

namespace Nat

/-- The multiplicative submonoid of positive naturals whose prime divisors
belong to `S`. It is generated by the values of primes in `S`. -/
def primeSupportedIndices (S : Set Nat.Primes) : Submonoid ℕ :=
  Submonoid.closure (Subtype.val '' S)

/-- A natural belongs to the prime-supported submonoid precisely when it is
positive and every prime divisor belongs to the supporting set. -/
theorem mem_primeSupportedIndices_iff {S : Set Nat.Primes} {n : ℕ} :
    n ∈ primeSupportedIndices S ↔ 0 < n ∧ ∀ p : Nat.Primes, p.1 ∣ n → p ∈ S := by
  constructor
  · intro hn
    refine Submonoid.closure_induction
      (motive := fun m _ => 0 < m ∧ ∀ p : Nat.Primes, p.1 ∣ m → p ∈ S)
      ?_ ?_ ?_ hn
    · intro m hm
      obtain ⟨p, hp, rfl⟩ := hm
      refine ⟨p.2.pos, fun q hq => ?_⟩
      have hpq : q = p := Subtype.ext ((prime_dvd_prime_iff_eq q.2 p.2).mp hq)
      exact hpq ▸ hp
    · constructor
      · exact zero_lt_one
      · intro p hp
        exact (p.2.not_dvd_one hp).elim
    · intro m k hm hk hm' hk'
      refine ⟨mul_pos hm'.1 hk'.1, fun p hp => ?_⟩
      rcases p.2.dvd_mul.mp hp with hpm | hpk
      · exact hm'.2 p hpm
      · exact hk'.2 p hpk
  · rintro ⟨hn, hs⟩
    rw [← prod_primeFactorsList hn.ne']
    apply (primeSupportedIndices S).list_prod_mem
    intro p hp
    apply Submonoid.subset_closure
    exact ⟨⟨p, prime_of_mem_primeFactorsList hp⟩,
      hs ⟨p, prime_of_mem_primeFactorsList hp⟩ (dvd_of_mem_primeFactorsList hp), rfl⟩

/-- The same criterion in the factorization form used by procyclic exponents. -/
theorem mem_primeSupportedIndices_iff_factorization {S : Set Nat.Primes} {n : ℕ} :
    n ∈ primeSupportedIndices S ↔
      0 < n ∧ ∀ p : Nat.Primes, n.factorization p.1 ≠ 0 → p ∈ S := by
  rw [mem_primeSupportedIndices_iff]
  constructor
  · rintro ⟨hn, hs⟩
    exact ⟨hn, fun p hp => hs p (dvd_of_factorization_pos hp)⟩
  · rintro ⟨hn, hs⟩
    exact ⟨hn, fun p hp => hs p (p.2.factorization_pos_of_dvd hn.ne' hp).ne'⟩

/-- For finite support, prime-supported indices are precisely the numbers factored
over that support, even when the finite set contains nonprime naturals. -/
theorem mem_primeSupportedIndices_iff_factoredNumbers (s : Finset ℕ) (n : ℕ) :
    n ∈ primeSupportedIndices {p : Nat.Primes | p.1 ∈ s} ↔ n ∈ factoredNumbers s := by
  constructor
  · intro hn
    apply mem_factoredNumbers'.mpr
    intro p hp hpn
    exact (mem_primeSupportedIndices_iff.mp hn).2 ⟨p, hp⟩ hpn
  · intro hn
    exact mem_primeSupportedIndices_iff.mpr
      ⟨Nat.pos_of_ne_zero (ne_zero_of_mem_factoredNumbers hn),
        fun p hp => (mem_factoredNumbers'.mp hn) p.1 p.2 hp⟩

/-- A supporting prime itself belongs to its generated submonoid. -/
theorem prime_mem_primeSupportedIndices_iff {S : Set Nat.Primes} (p : Nat.Primes) :
    p.1 ∈ primeSupportedIndices S ↔ p ∈ S := by
  rw [mem_primeSupportedIndices_iff]
  constructor
  · exact fun h => h.2 p (dvd_refl _)
  · intro hp
    refine ⟨p.2.pos, fun q hq => ?_⟩
    have hpq : q = p := Subtype.ext ((prime_dvd_prime_iff_eq q.2 p.2).mp hq)
    exact hpq ▸ hp

/-- Enlarging the allowed primes enlarges the submonoid. -/
theorem primeSupportedIndices_mono {S T : Set Nat.Primes} (hST : S ⊆ T) :
    primeSupportedIndices S ≤ primeSupportedIndices T :=
  Submonoid.closure_mono (Set.image_mono hST)

@[simp] theorem primeSupportedIndices_empty : primeSupportedIndices ∅ = ⊥ := by
  apply le_antisymm
  · apply Submonoid.closure_le.mpr
    rintro _ ⟨p, hp, rfl⟩
    cases hp
  · exact bot_le

@[simp] theorem mem_primeSupportedIndices_univ {n : ℕ} :
    n ∈ primeSupportedIndices (Set.univ : Set Nat.Primes) ↔ 0 < n := by
  simp [mem_primeSupportedIndices_iff]

@[simp] theorem not_mem_primeSupportedIndices_zero (S : Set Nat.Primes) :
    0 ∉ primeSupportedIndices S := by
  simp [mem_primeSupportedIndices_iff]

end Nat

namespace ProfiniteGrp

universe u

/-- For positive `n`, the `n`-th power image has index `n` exactly when
its prime divisors occur with infinite exponent in the torsion-free group.

This expresses the supported-index description in Neukirch–Schmidt–Wingberg, *Cohomology of
Number Fields*, Ch. I §7, before Proposition (1.7.7), using Mathlib’s prime-generated
submonoids. -/
theorem powerImage_index_eq_iff_primeSupportedIndices (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (hfree : IsMulTorsionFree G) (n : ℕ) (hn : 0 < n) :
    (powerImage G hG n : Subgroup G).index = n ↔
      n ∈ Nat.primeSupportedIndices {p | hG.exponents p = ⊤} := by
  rw [powerImage_index_eq_iff_exponents_top_of_isMulTorsionFree G hG hfree n hn,
    Nat.mem_primeSupportedIndices_iff_factorization]
  exact ⟨fun h => ⟨hn, h⟩, fun h => h.2⟩

/-- The index of every open subgroup of a torsion-free procyclic profinite
group is positive and supported on the infinite-exponent primes. The subgroup
itself is recovered by `openSubgroup_eq_powerImage` at this index.

The torsion-free supported-index idea comes from Neukirch–Schmidt–Wingberg, *Cohomology of
Number Fields*, Ch. I §7, before Proposition (1.7.7). -/
theorem openSubgroup_index_mem_primeSupportedIndices (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (hfree : IsMulTorsionFree G) (H : OpenSubgroup G) :
    (H : Subgroup G).index ∈
      Nat.primeSupportedIndices {p | hG.exponents p = ⊤} := by
  have hfinite : Finite (G ⧸ (H : Subgroup G)) :=
    Subgroup.quotient_finite_of_isOpen (H : Subgroup G) H.isOpen'
  have hpos : 0 < (H : Subgroup G).index :=
    Nat.pos_of_ne_zero (Subgroup.index_ne_zero_iff_finite.mpr hfinite)
  apply (powerImage_index_eq_iff_primeSupportedIndices G hG hfree _ hpos).mp
  rw [← openSubgroup_eq_powerImage G hG H]

end ProfiniteGrp
