/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import ProfiniteGroups.ProcyclicBaseMap
public import Mathlib.Topology.Algebra.OpenSubgroup
public import Mathlib.Topology.Algebra.Group.ClosedSubgroup

/-!
# Powers and open subgroups of procyclic profinite groups

For a supplied proof of procyclicity, the pointwise power map is a continuous
homomorphism. Its range is a closed subgroup, topologically generated by the
corresponding power of any topological generator. Positive powers give open
subgroups whose indices divide the exponent; conversely every open subgroup is
the power-image subgroup at its index.

The index of a positive power image need not equal the exponent, and the zero
power image is bottom with no general openness assertion. This classifies
*open* subgroups; it does not classify all closed subgroups.

## Using the power-image API

Supply `hG : IsProcyclic G` explicitly to `powerHom` and `powerImage`.
Use `mem_powerImage_iff` to obtain an actual root in `G`. To work with the image
as a profinite group, use `powerHomToImage`; `powerHomToImage_apply_coe`
computes its value back in `G`, and `powerHomToImage_surjective` supplies
preimages. No chosen topological generator is needed for these constructions.

For `hn : 0 < n`, `powerOpenSubgroup G hG n hn` packages the same subgroup
with openness; `powerOpenSubgroup_toSubgroup` forgets this packaging.
`openSubgroup_eq_powerImage` recovers an arbitrary open subgroup from its index,
and `openSubgroup_eq_of_index_eq` gives uniqueness at a fixed index. These results
do not assert that every positive integer occurs as an index.
-/

@[expose] public section

open Set Function

set_option linter.style.haveILetI false

universe u

namespace ProfiniteGrp

/-- The multiplication of a procyclic profinite group is commutative. No
alternative group structure is installed on the underlying type. -/
theorem IsProcyclic.isMulCommutative {G : ProfiniteGrp.{u}} (hG : IsProcyclic G) :
    IsMulCommutative G := by
  obtain ⟨g, hg⟩ := hG
  have hcentral (x : G) : Commute g x := by
    have heq := (hg : DenseRange fun k : ℤ => g ^ k).equalizer
      (continuous_const.mul continuous_id) (continuous_id.mul continuous_const)
      (by
        funext k
        exact (Commute.self_zpow g k).eq)
    exact congrFun heq x
  refine ⟨⟨fun x y => ?_⟩⟩
  have heq := (hg : DenseRange fun k : ℤ => g ^ k).equalizer
    (continuous_const.mul continuous_id) (continuous_id.mul continuous_const)
    (by
      funext k
      exact ((hcentral x).symm.zpow_right k).eq)
  exact congrFun heq y

/-- The continuous homomorphism that really sends `x` to `x ^ n`. -/
def powerHom (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) (n : ℕ) : G →ₜ* G :=
  letI := hG.isMulCommutative
  ⟨{
    toFun := fun x => x ^ n
    map_one' := one_pow n
    map_mul' := fun x y =>
      (show Commute x y from IsMulCommutative.is_comm.comm x y).mul_pow n
  }, continuous_pow n⟩

/-- Evaluation of the continuous power homomorphism is the ordinary natural
power in the original group, with no change of its group structure. -/
@[simp] theorem powerHom_apply (G : ProfiniteGrp.{u}) (hG : IsProcyclic G)
    (n : ℕ) (x : G) : powerHom G hG n x = x ^ n := rfl

/-- The zeroth power endomorphism is the constant identity map. -/
theorem powerHom_zero (G : ProfiniteGrp.{u}) (hG : IsProcyclic G)
    (x : G) : powerHom G hG 0 x = 1 := by simp

/-- The first power endomorphism is the identity map. -/
theorem powerHom_one (G : ProfiniteGrp.{u}) (hG : IsProcyclic G)
    (x : G) : powerHom G hG 1 x = x := by simp

/-- Composition of power endomorphisms is multiplication of exponents. -/
theorem powerHom_comp (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) (m n : ℕ) :
    (powerHom G hG m).comp (powerHom G hG n) = powerHom G hG (n * m) := by
  ext x
  simp [pow_mul]

/-- The closed range of the continuous pointwise power map. -/
def powerImage (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) (n : ℕ) :
    ClosedSubgroup G :=
  ⟨(powerHom G hG n).toMonoidHom.range,
    (isCompact_range (powerHom G hG n).continuous_toFun).isClosed⟩

/-- Membership in the closed power-image subgroup has an actual n-th-root
witness in the original group, not just a limit of powers. -/
@[simp] theorem mem_powerImage_iff (G : ProfiniteGrp.{u}) (hG : IsProcyclic G)
    (n : ℕ) (x : G) : x ∈ powerImage G hG n ↔ ∃ y : G, y ^ n = x := by
  change (∃ y : G, powerHom G hG n y = x) ↔ _
  rfl

/-- Forgetting closedness from `powerImage` gives the actual algebraic range
of `powerHom`; there is no additional closure operation in this projection. -/
theorem powerImage_subgroup (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) (n : ℕ) :
    (powerImage G hG n : Subgroup G) = (powerHom G hG n).toMonoidHom.range := rfl

/-- Every topological generator gives a generator for the closed power image. -/
theorem powerImage_eq_topologicalClosure_zpowers (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (g : G) (hg : IsTopologicalGenerator G g) (n : ℕ) :
    (powerImage G hG n : Subgroup G) =
      (Subgroup.zpowers (g ^ n)).topologicalClosure := by
  let P := powerImage G hG n
  apply le_antisymm
  · intro x hx
    obtain ⟨y, rfl⟩ := (mem_powerImage_iff G hG n x).mp hx
    have hclosed : IsClosed ((Subgroup.zpowers (g ^ n)).topologicalClosure : Set G) :=
      Subgroup.isClosed_topologicalClosure _
    have hpre : closure (range (fun k : ℤ => g ^ k)) ⊆
        (fun z : G => z ^ n) ⁻¹' ((Subgroup.zpowers (g ^ n)).topologicalClosure : Set G) :=
      closure_minimal (by
        rintro z ⟨k, rfl⟩
        change (g ^ k) ^ n ∈ (Subgroup.zpowers (g ^ n)).topologicalClosure
        apply Subgroup.le_topologicalClosure _
        rw [Subgroup.mem_zpowers_iff]
        refine ⟨k, ?_⟩
        calc
          (g ^ n) ^ k = g ^ ((n : ℤ) * k) := by rw [← zpow_natCast, zpow_mul]
          _ = g ^ (k * (n : ℤ)) := by rw [mul_comm]
          _ = (g ^ k) ^ n := by rw [← zpow_natCast, zpow_mul])
        (hclosed.preimage (continuous_pow n))
    exact hpre (by simpa only [hg.closure_range] using (Set.mem_univ y))
  · apply Subgroup.topologicalClosure_minimal _
      (Subgroup.zpowers_le.mpr ((mem_powerImage_iff G hG n (g ^ n)).mpr ⟨g, rfl⟩))
    exact P.isClosed'

/-- The subgroup of n-th powers is independent of the chosen generator. -/
theorem topologicalClosure_zpowers_pow_eq (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (g k : G) (hg : IsTopologicalGenerator G g)
    (hk : IsTopologicalGenerator G k) (n : ℕ) :
    (Subgroup.zpowers (g ^ n)).topologicalClosure =
      (Subgroup.zpowers (k ^ n)).topologicalClosure := by
  rw [← powerImage_eq_topologicalClosure_zpowers G hG g hg n,
    ← powerImage_eq_topologicalClosure_zpowers G hG k hk n]

/-- The surjective continuous power map, now regarded as taking values in its
actual closed (and hence profinite) range. -/
def powerHomToImage (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) (n : ℕ) :
    G →ₜ* ofClosedSubgroup (powerImage G hG n) :=
  ⟨{
    toFun := fun x => ⟨x ^ n, (mem_powerImage_iff G hG n _).mpr ⟨x, rfl⟩⟩
    map_one' := by apply Subtype.ext; change (1 : G) ^ n = 1; simp
    map_mul' := by
      intro x y
      apply Subtype.ext
      exact (powerHom G hG n).map_mul x y
  }, (powerHom G hG n).continuous_toFun.subtype_mk
    (fun x => (mem_powerImage_iff G hG n _).mpr ⟨x, rfl⟩)⟩

/-- Coercing the value of the surjective power map from its closed-subgroup
codomain back to `G` recovers the ordinary natural power. -/
@[simp] theorem powerHomToImage_apply_coe (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (x : G) :
    (powerHomToImage G hG n x).1 = x ^ n := rfl

/-- Every element of the power image has a preimage under the continuous
homomorphism into the closed-subgroup model. -/
theorem powerHomToImage_surjective (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) : Surjective (powerHomToImage G hG n) := by
  intro x
  obtain ⟨y, hy⟩ := (mem_powerImage_iff G hG n x.1).mp x.2
  exact ⟨y, Subtype.ext hy⟩

/-- The n-th power of a topological generator is an actual topological
generator of the closed power image, viewed as a profinite group. -/
theorem powerHomToImage_isTopologicalGenerator (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (g : G) (hg : IsTopologicalGenerator G g) (n : ℕ) :
    IsTopologicalGenerator (ofClosedSubgroup (powerImage G hG n))
      (powerHomToImage G hG n g) :=
  hg.map (powerHomToImage G hG n) (powerHomToImage_surjective G hG n)

/-- Every closed power image of a procyclic profinite group is procyclic,
including the zero-th power image. -/
theorem powerImage_isProcyclic (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) :
    IsProcyclic (ofClosedSubgroup (powerImage G hG n)) := by
  obtain ⟨g, hg⟩ := hG
  exact ⟨powerHomToImage G ⟨g, hg⟩ n g,
    powerHomToImage_isTopologicalGenerator G ⟨g, hg⟩ g hg n⟩

/-- The zero-th power image is the trivial subgroup; no openness is claimed. -/
@[simp] theorem powerImage_zero (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) :
    (powerImage G hG 0 : Subgroup G) = ⊥ := by
  ext x
  change (∃ y : G, y ^ 0 = x) ↔ x = 1
  simp [eq_comm]

/-- Every element is a first power, so its image is the top subgroup. -/
@[simp] theorem powerImage_one (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) :
    (powerImage G hG 1 : Subgroup G) = ⊤ := by
  ext x
  change (∃ y : G, y ^ 1 = x) ↔ True
  simp

/-- Every power image is normal, since the original group is commutative. -/
instance powerImage_normal (G : ProfiniteGrp.{u}) (hG : IsProcyclic G) (n : ℕ) :
    (powerImage G hG n : Subgroup G).Normal :=
  letI : IsMulCommutative G := hG.isMulCommutative
  Subgroup.normal_of_isMulCommutative _

private theorem zpowers_quotient_eq_top_of_finOrder {G : ProfiniteGrp.{u}}
    {H : Subgroup G} [H.Normal] (hclosed : IsClosed (H : Set G))
    {g : G} (hg : IsTopologicalGenerator G g)
    (hfin : IsOfFinOrder ((QuotientGroup.mk' H) g)) :
    Subgroup.zpowers ((QuotientGroup.mk' H) g) = ⊤ := by
  haveI : T1Space (G ⧸ H) := QuotientGroup.t1Space_iff.mpr hclosed
  haveI : Finite (Subgroup.zpowers ((QuotientGroup.mk' H) g)) := finite_zpowers.mpr hfin
  have hd : DenseRange (fun k : ℤ => ((QuotientGroup.mk' H) g) ^ k) := by
    have hd' := (QuotientGroup.mk'_surjective H).denseRange.comp hg
      (QuotientGroup.continuous_mk (N := H))
    simpa only [Function.comp_def, map_zpow] using hd'
  apply SetLike.ext'
  change ((Subgroup.zpowers ((QuotientGroup.mk' H) g) : Subgroup (G ⧸ H)) :
    Set (G ⧸ H)) = univ
  calc
    _ = closure (Subgroup.zpowers ((QuotientGroup.mk' H) g) : Set (G ⧸ H)) :=
      (Set.toFinite _).isClosed.closure_eq.symm
    _ = univ := by simpa only [Subgroup.coe_zpowers] using hd.closure_range

/-- The quotient by a positive power image is generated by the image of any
supplied topological generator. In particular it is an abstract cyclic group. -/
theorem powerImage_quotient_zpowers_eq_top (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (g : G) (hg : IsTopologicalGenerator G g)
    (n : ℕ) (hn : 0 < n) :
    Subgroup.zpowers ((QuotientGroup.mk' (powerImage G hG n : Subgroup G)) g) = ⊤ := by
  let H := (powerImage G hG n : Subgroup G)
  have hpow : ((QuotientGroup.mk' H) g) ^ n = 1 := by
    rw [← map_pow]
    exact (QuotientGroup.eq_one_iff (g ^ n)).mpr
      ((mem_powerImage_iff G hG n (g ^ n)).mpr ⟨g, rfl⟩)
  exact zpowers_quotient_eq_top_of_finOrder (powerImage G hG n).isClosed' hg
    (isOfFinOrder_iff_pow_eq_one.mpr ⟨n, hn, hpow⟩)

/-- The positive-power quotient is finite and cyclic. -/
theorem powerImage_quotient_isCyclic (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (g : G) (hg : IsTopologicalGenerator G g)
    (n : ℕ) (hn : 0 < n) :
    IsCyclic (G ⧸ (powerImage G hG n : Subgroup G)) :=
  isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨_, powerImage_quotient_zpowers_eq_top G hG g hg n hn⟩

/-- For positive `n`, the index of the subgroup of n-th powers divides `n`.
There is no general equality: torsion can make the index smaller. -/
theorem powerImage_index_dvd (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (hn : 0 < n) :
    (powerImage G hG n : Subgroup G).index ∣ n := by
  obtain ⟨g, hg⟩ := hG
  have hG : IsProcyclic G := ⟨g, hg⟩
  let H := (powerImage G hG n : Subgroup G)
  have hgen : Subgroup.zpowers ((QuotientGroup.mk' H) g) = ⊤ :=
    powerImage_quotient_zpowers_eq_top G hG g hg n hn
  have hpow : ((QuotientGroup.mk' H) g) ^ n = 1 := by
    rw [← map_pow]
    exact (QuotientGroup.eq_one_iff (g ^ n)).mpr
      ((mem_powerImage_iff G hG n (g ^ n)).mpr ⟨g, rfl⟩)
  calc
    H.index = Nat.card (G ⧸ H) := H.index_eq_card
    _ = orderOf ((QuotientGroup.mk' H) g) :=
      (orderOf_eq_card_of_zpowers_eq_top hgen).symm
    _ ∣ n := orderOf_dvd_of_pow_eq_one hpow

/-- Positive power images have finite index. -/
theorem powerImage_finiteIndex (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (hn : 0 < n) :
    (powerImage G hG n : Subgroup G).FiniteIndex := by
  refine ⟨?_⟩
  intro hz
  have hdiv := powerImage_index_dvd G hG n hn
  rw [hz] at hdiv
  omega

/-- The positive-power quotient is finite. Its cyclicity and the generating
class are given by `powerImage_quotient_isCyclic` and
`powerImage_quotient_zpowers_eq_top`. -/
theorem powerImage_quotient_finite (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (hn : 0 < n) :
    Finite (G ⧸ (powerImage G hG n : Subgroup G)) := by
  haveI := powerImage_finiteIndex G hG n hn
  infer_instance

/-- Positive-power images are open subgroups of finite index. -/
theorem powerImage_isOpen (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (hn : 0 < n) :
    IsOpen ((powerImage G hG n : Subgroup G) : Set G) := by
  haveI := powerImage_finiteIndex G hG n hn
  exact (powerImage G hG n : Subgroup G).isOpen_of_isClosed_of_finiteIndex
    (powerImage G hG n).isClosed'

/-- Package a positive power image as an open subgroup. -/
def powerOpenSubgroup (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (hn : 0 < n) : OpenSubgroup G :=
  ⟨(powerImage G hG n : Subgroup G), powerImage_isOpen G hG n hn⟩

/-- The open-subgroup packaging of a positive power image has exactly the
same underlying subgroup as the closed power image. -/
@[simp] theorem powerOpenSubgroup_toSubgroup (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (n : ℕ) (hn : 0 < n) :
    (powerOpenSubgroup G hG n hn : Subgroup G) = (powerImage G hG n : Subgroup G) := rfl

/-- Any open subgroup of a procyclic profinite group is precisely the image
of the power map at its actual index (with no extra normality assumption). -/
theorem openSubgroup_eq_powerImage (G : ProfiniteGrp.{u}) (hG : IsProcyclic G)
    (H : OpenSubgroup G) :
    (H : Subgroup G) = (powerImage G hG (H : Subgroup G).index : Subgroup G) := by
  haveI : IsMulCommutative G := hG.isMulCommutative
  haveI : (H : Subgroup G).Normal := Subgroup.normal_of_isMulCommutative _
  haveI : Finite (G ⧸ (H : Subgroup G)) :=
    Subgroup.quotient_finite_of_isOpen (H : Subgroup G) H.isOpen'
  haveI : (H : Subgroup G).FiniteIndex := Subgroup.finiteIndex_of_finite_quotient
  have hpos : 0 < (H : Subgroup G).index :=
    Nat.pos_of_ne_zero Subgroup.FiniteIndex.index_ne_zero
  have hle : (powerImage G hG (H : Subgroup G).index : Subgroup G) ≤ H := by
    intro x hx
    obtain ⟨y, rfl⟩ := (mem_powerImage_iff G hG _ x).mp hx
    exact (H : Subgroup G).pow_index_mem y
  have hidx : (powerImage G hG (H : Subgroup G).index : Subgroup G).index =
      (H : Subgroup G).index :=
    Nat.dvd_antisymm (powerImage_index_dvd G hG _ hpos)
      (Subgroup.index_dvd_of_le hle)
  have heq : (powerImage G hG (H : Subgroup G).index : Subgroup G) = H := by
    by_contra hnot
    have hlt : (powerImage G hG (H : Subgroup G).index : Subgroup G) < H :=
      lt_of_le_of_ne hle hnot
    haveI : (powerImage G hG (H : Subgroup G).index : Subgroup G).FiniteIndex := by
      refine ⟨?_⟩
      intro hz
      have hdiv := powerImage_index_dvd G hG _ hpos
      rw [hz] at hdiv
      omega
    have hltidx := Subgroup.index_strictAnti hlt
    rw [hidx] at hltidx
    exact (Nat.lt_irrefl _ hltidx)
  exact heq.symm

/-- The same classification for an ordinary subgroup accompanied by openness. -/
theorem subgroup_eq_powerImage_of_isOpen (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (H : Subgroup G) (hH : IsOpen (H : Set G)) :
    H = (powerImage G hG H.index : Subgroup G) :=
  openSubgroup_eq_powerImage G hG ⟨H, hH⟩

/-- Open subgroups with equal index coincide. -/
theorem openSubgroup_eq_of_index_eq (G : ProfiniteGrp.{u})
    (hG : IsProcyclic G) (H K : OpenSubgroup G)
    (hindex : (H : Subgroup G).index = (K : Subgroup G).index) : H = K := by
  apply OpenSubgroup.toSubgroup_injective
  rw [openSubgroup_eq_powerImage G hG H,
    openSubgroup_eq_powerImage G hG K, hindex]

end ProfiniteGrp
